---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_drafter:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: release-drafter/release-drafter@v5
        with:
          config-path: .github/release-drafter.yml
          token: ${{ secrets.GITHUB_TOKEN }}
